[package]
name = "vars"
version = "0.1.0"
authors = ["Ronit halder <ronit.crj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
